### ISSUE TITLE
Invalid 'row.names' length

### ISSUE THREAD

**Issue by eamoncaddigan** [WIDworld/wid-r-tool#1]
I've seen this error on a few queries. At first I thought it only happend when data aren't available, but now I'm not sure what's causing it.

This code, from the documentation, works fine.

``` r
data <- download_wid(
  indicators = "sptinc", # Shares of pre-tax national income
  areas = "US", # In the United States
  years = 2010:2015, # Time period: 2010-2015
  perc = "p99p100" # Top 1% only
)
```

However, just querying one year raises an error:

``` r
data <- download_wid(
  indicators = "sptinc", # Shares of pre-tax national income
  areas = "US", # In the United States
  years = 2015, # Just 2015
  perc = "p99p100" # Top 1% only
)
#> Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
#>  invalid 'row.names' length
```

I'm using latest version from GitHub.

**Comment by thomasblanchet** [comment]
It should be OK now with the latest version. The way I was getting rid of some weird row names occasionally caused problems, in particular when the result was empty.

**Comment by eamoncaddigan** [comment]
I can confirm that it's working for me now.
