### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by itsener** [WIDworld/wid-r-tool#2]
Hi Thomas,
In my case, after installing the package R throws an error: can't find function "download_wid". Do you know what could cause this problem?
Thanks in advance,
Inna
![screen shot 2019-01-12 at 20 33 19](https://user-images.githubusercontent.com/43468505/51077616-6f0e4100-16a9-11e9-81f8-34bbcd14e6dc.png)

**Comment by itsener** [comment]
ah, thanks a lot, everything works now! I must have missed it somewhere on the way. Btw, I've noticed that one of the countries in the WID webpage is not displayed correctly (see screen attached)
![screen shot 2019-01-13 at 15 51 36](https://user-images.githubusercontent.com/43468505/51086829-7ede6180-174b-11e9-93bc-bb07a5a80feb.png)

**Comment by thomasblanchet** [comment]
OK, thanks for signaling, I'll have a look at it.
