### ISSUE TITLE
Importing data returns: "Error in parse"

### ISSUE THREAD

**Issue by SnupSnurre** [WIDworld/wid-r-tool#3]
Hi Thomas, 

Thank you for a great package! I have been working with it quite a bit, and it is awesome! However, until now, I have only been working with a few countries at a time. Trying to import a bunch of different countries, I use the following code: 

```
WID <- download_wid(
  indicators = "sptinc", # Share of pre-tax national income
  areas = c("AT", "BE", "CH", "CZ", "DE", "EE", "ES", "FI", "FR"), # Specifying relevant countries
  years = 1989:2019, # Specifying time period
  perc = c("p99p100", "p90p100"), # Specifying relevant percentiles
  ages = 992, # Import adults only
  metadata = TRUE # Include metadata
)
```
However, it returns the following error:

```
Error in parse(text = content(response_request, as = "text", encoding = "UTF-8")) : 
  string at line 1 containing Unicode escapes not in this locale
is too long (max 10000 chars)
```

It is quite strange. If I remove FR from the vector, the code runs fine. However, I can easily import data from France alone or with a few other countries as well. What is going on here?

**Comment by thomasblanchet** [comment]
Hi @SnupSnurre,

Turns out that the way I was parsing the server response did not scale well. I just fixed that part. You can re-install the package from GitHub and it should work now.

**Comment by SnupSnurre** [comment]
Thank you very much for the fast update! Just want to confirm that it works as expected now. Thank you.
