### ISSUE TITLE
Error in "errorMessage":"body size is too long" : NA/NaN argument

### ISSUE THREAD

**Issue by hhsievertsen** [WIDworld/wid-r-tool#4]
Hi,
thanks for creating this excellent package.

I was trying to download data for all countries, using the following:
`
wid_data <- download_wid(
indicators = "sptinc", 
  areas = c("all"), 
  verbose = TRUE,
  perc = c( "p99p100") 
)
`

But I get the error message

> Error in "errorMessage":"body size is too long" : NA/NaN argument

I guess the dataset is too big. It works well if I specify one specific country. But in what case could I then use the "all" option in areas? Sorry if the question is trivial.

Thanks again,
Hans

**Comment by thomasblanchet** [comment]
Given recents updates to the database, the way I was making some requests was becoming too much for the server to handle. I just made a fix that should address it, you'll just have to update the package.

**Comment by hhsievertsen** [comment]
Brilliant, Works! Thanks a lot
