### ISSUE TITLE
"more columns than column names" if metadata=T

### ISSUE THREAD

**Issue by clukewatson** [WIDworld/wid-r-tool#5]
Howdy, 

I am trying to download data and if I request metadata, then I get the following error: "Error in read.table(file = file, header = header, sep = sep, quote = quote,  :  more columns than column names".

Any thoughts?

# does not work, yields error
data <- download_wid(
  indicators = "sptinc", # Shares of personal wealth 
  years = 2015, # Time period: 2015
  areas = "all", # In France
  perc = c("p0p50", "p99p100"), # Top 1% and top 10%
  metadata = T # Also request metadata
)
# works, no error
data <- download_wid(
  indicators = "sptinc", # Shares of personal wealth 
  years = 2015, # Time period: 2015
  areas = "all", # In France
  perc = c("p0p50", "p99p100"), # Top 1% and top 10%
  metadata = F # do not request metadata
)

**Comment by thomasblanchet** [comment]
Hi,
There was indeed a bug with the metadata request. I just fixed it.
