### ISSUE TITLE
Decomposing wealth shares for the 1%

### ISSUE THREAD

**Issue by eteitelbaum** [WIDworld/wid-r-tool#8]
Hello! Thanks for developing this tool. Last year I made a slide for my course that used the WID to decompose the wealth shares of the top 1% in the U.S. Here is the code that worked for me last year to download the data: 

`library(wid)
data <- download_wid(
  indicators = "shweal", # Shares of personal wealth
  areas = "US", # In the U.S. 
  perc = c("p99p99.5", "p99.5p99.9", "p99.9p99.99", "p99.99p100"), # Shares of 1%
  year = 1960:2019
)`

This year when I run the same code I get the full series from 1960-2019 for the top .01% but only the first couple of years for the other three groups (.1-.01, .5-.1 and 1-.5). Are the data for these three groups still available? 

Also, last year when I downloaded the data I only got the "j" series (50-50 split) but this year I also see "t." And in some other series I am also seeing "i" in addition to "t" and "j." How can I specify that I only want "j" in the code?

**Comment by thomasblanchet** [comment]
The percentiles that get downloaded are those that are actually stored in the database, and it's possible that some of them disappeared, we'll look into this. I believe the information must still be there though, you would need to download `"pXp100"` (top shares) and recompute brackets shares from this.

If you only need "j" series you can specify `pop = "j"` as an argument.
