### ISSUE TITLE
Has the Syntax Changed? 

### ISSUE THREAD

**Issue by eteitelbaum** [WIDworld/wid-r-tool#9]
I am trying to run some code I have in an R Markdown file I use to compile my lecture slides: 

```
data <- download_wid(
	indicators = "shweal992", # Shares of personal wealth
	areas = "US", # In the U.S.
	perc = c("p90p100", "p99p100") # Top 10% and top 1%
)
```

But it no longer works. I get a `check_indicators(indicators)` error that says the indicators must be six letter codes. However, I don't see any summary codes in the (summary table)[https://wid.world/summary-table/] on the WID website.

**Comment by thomasblanchet** [comment]
I shouldn't have changed but it's possible the command became more strict after the last rewrite a year ago. The "992" part of the code should be passed using the "ages" argument. For a description of WID codes please refer to https://wid.world/codes-dictionary/.
